#!/bin/bash

cachedir="$(pacman-conf CacheDir)"
DOWNLOADARGS='-c -s4 -k5M -x8 -j8 -t10 --console-log-level=warn --file-allocation=falloc --retry-wait=5 --summary-interval=0 -d '$cachedir''

if [ "$OSTYPE" = "linux-gnu" ]; then
	[ "`whoami`" = "root" ] || exec sudo "$0" "$@"
fi

if [ $(command -v pacman) ] && echo "$@" | grep -q "\-S"; then
  # Download unfinished jobs
  [ $(command -v aria2c) ] || pacman -S --noconfirm --needed aria2
  [ -f app-fast.list ] && echo "Downloading unfinished jobs." && aria2c $DOWNLOADARGS -i app-fast.list

  # Create new jobs
  echo -e "\e[1;42m Downloading: \e[0m" "${@:2}"
  pacman $@ --print --print-format "%l" | grep -E -o -e "(ht|f)tp[s]?://[^\']+" | tee app-fast.list && aria2c -c $DOWNLOADARGS -i app-fast.list
  #pacman $@ --print-format "%n" | tee pacfast.list && aria2c -c $DOWNLOADARGS -i pacfast.list

  
  echo -e "\e[1;42m Installing: \e[0m" "${@:2}"
  pacman $(echo "$1" | sed "s/y//g") ${@:2} && rm -f pacfast.list && exit 0
  exit 1
fi

#&> /dev/null
