#!/bin/bash

function get_core_urls ()
{
   echo "$MIRRORS" | sed "s,$,core/os/${ARCH}/core.db.tar.gz,g"
}

function get_gcc_urls ()
{
   echo "$MIRRORS" | sed "s,$,core/os/${ARCH}/${GCC_URL},g"
}

On_White='\e[1;30;107m'
On_Green='\e[1;97;42m'
echo -e "\n\e ${On_Green} PacFast ${On_White} Gets the fastest 50 mirrors \e[0m"
echo "Please wait..."

# arch
ARCH=`(uname -m) 2>/dev/null` || ARCH=x86_64

# var containing mirror urls
MIRRORS=$(curl -LksS -o - 'https://www.archlinux.org/mirrors/status/json/' | \
          sed 's,{,\n{,g' | sed -n '/rsync/d; /pct": 1.0/p' | sed 's,^.*"url": "\([^"]\+\)".*,\1,g')
          
core_urls=echo "$MIRRORS" | sed "s,$,core/os/${ARCH}/core.db.tar.gz,g"

gcc_urls=echo "$MIRRORS" | sed "s,$,core/os/${ARCH}/${GCC_URL},g"

# the gcc file
GCC_URL=$( curl -LksSH --url ftp://ftp.archlinux.org/core/os/${ARCH}/ 2>/dev/null | sed -n 's/^.*\ \(gcc-[0-9]\+.*.tar.xz.sig\)\ -.*$/\1/gp' );
{
   # faster as primarily used to pre-resolve dns for 2nd core test
   gcc_urls | xargs -I'{}' -P40 curl -Lks -o /dev/null -m 3 --retry 0 --no-keepalive -w '%{time_total}@%{speed_download}@%{url_effective}\n' --url '{}' |\
   sort -t@ -k2 -nr | head -n 50 | cut -d'@' -f3 | sed 's,core/os/'"${ARCH}/${GCC_URL}"',$repo/os/$arch,g'

   core_urls | xargs -I'{}' -P10 curl -Lks -o /dev/null -m 5 --retry 0 --no-keepalive -w '%{time_total}@%{speed_download}@%{url_effective}\n' --url '{}' |\
   sort -t@ -k2 -nr | head -n 50 | cut -d'@' -f3 | sed 's,core/os/'"${ARCH}"'/core.db.tar.gz,$repo/os/$arch,g'
} | sed 's,^,Server = ,g' | awk '{ if (!h[$0]) { print $0; h[$0]=1 } }' | tee /etc/pacman.d/mirrorlist >/dev/null

printf "%s\r%s%s" abcdefghijklmnopqrstuvwxyz $(tput el) "Finished\n"

exit 1
